// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdkyahapnibtxkyofbap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZka3lhaGFwbmlidHhreW9mYmFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ5NjgwNDEsImV4cCI6MjA1MDU0NDA0MX0.s7AoZMxB1iHF-jEgjBZo5XoqSMPE-w5mh31c0Q3V_mQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);